services:
  - type: web
    name: csv-agent-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --timeout 300 --workers 1 --bind 0.0.0.0:$PORT
    pythonVersion: "3.12.8"
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8

  - type: web
    name: csv-agent-frontend
    env: node
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://csv-agent-72hj.onrender.com
